name: ASP.NET Core CI

on: [push]

jobs:
  test:
    name: Test on .NET Core for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use .NET 2.2.108
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: dotnet build and test
      run: |
        dotnet build --configuration Debug
        dotnet test
        
  publish-webstore:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet publish --configuration Release WebStore/UI/WebStore/WebStore.csproj
    
    - uses: actions/upload-artifact@master
      with:
        name: webstore-${{ matrix.os }}
        path: WebStore/UI/WebStore/bin/Release/netcoreapp2.2/publish

  build-api:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet publish --configuration Release WebStore/Services/WebStore.ServicesHosting/WebStore.ServicesHosting.csproj
    
    - uses: actions/upload-artifact@master
      with:
        name: webstore-api-${{ matrix.os }}
        path: WebStore/Services/WebStore.ServiceHosting/bin/Release/netcoreapp2.2/publish
